### ISSUE TITLE
Manage buttons input as event ?

### ISSUE THREAD

**Issue by Sebwap** [pimoroni/displayhatmini-python#5]
Is there any way to manage buttons input as event ?

I currently handle this in an infinite loop in my program, but if you don't push the button at the good time, (when reading buttons status), then your input is not considered.

One idea would be to use pygame event manager to handle this, but I don't know if it's possible to map GPIO input to pygame events ?

Or should I have a separate thread for reading GPIO continuously ? That would be bad for processor usage on my poor zero 1 :( 

Any help will be appreciated !

**Comment by Gadgetoid** [comment]
Ahoy, sorry for the delay responding!

The buttons read LOW when they're triggered, so with this in mind you can use RPi.GPIO directly to attach an event detect and call a function when they read low. This just runs a loop on a thread in the background (iirc) but it's fast and low-level so you don't have to care about it.

Eg:

```python
from displayhatmini import DisplayHATMini, GPIO

display_hat = DisplayHATMini(None)


def handle_interrupt(pin):
    if pin == display_hat.BUTTON_A:
        # Do thing for BUTTON_A
        return
    if pin == display_hat.BUTTON_B:
        # Do thing for BUTTON_B
        return


for pin in (displayhatmini.BUTTON_A, displayhatmini.BUTTON_B):
   GPIO.add_event_detect(pin, GPIO.FALLING, callback=handle_interrupt)

while True:
    pass
```

I think you can then use `pygame.event.post` to push it into the event queue as either a fake keypress or a user event.

I'll see if I can whip up an example for this, because it's a good idea.

**Comment by Sebwap** [comment]
Thanks for the answer !
I manage to do it with an infinite loop in my program, but it consume lots of CPU on a pi 0 W (~0.20)

Hope this solution would be better ?

**Comment by Gadgetoid** [comment]
It should be considerably better, although I suspect you'll still get a lot of CPU overhead from the code to mangle PyGame's display buffer into bytes to send to the display.

PR inbound with example and a new library feature to support it: https://github.com/pimoroni/displayhatmini-python/pull/10

**Comment by Gadgetoid** [comment]
You should now be able to upgrade to 0.0.2 and try - https://github.com/pimoroni/displayhatmini-python/blob/v0.0.2/examples/pygame-button-interrupt.py
